# Generated by Django 4.2.17 on 2026-02-01 18:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0009_readd_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Eggslist', max_length=128, verbose_name='site name')),
                ('tagline', models.CharField(default='Find Farmers Near You', max_length=256, verbose_name='tagline')),
                ('site_description', models.TextField(default="Your virtual Farmer's Market, where you can buy, sell, and connect with local farmers and gardeners to keep your food fresh and local!", verbose_name='site description')),
                ('primary_color', models.CharField(default='#D4A843', max_length=7, verbose_name='primary color (hex)')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='branding', verbose_name='logo')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='branding', verbose_name='favicon')),
                ('copyright_text', models.CharField(default='Eggslist. All rights reserved.', max_length=256, verbose_name='copyright text')),
                ('cta_text', models.CharField(default='Sign up to start buying and selling local food!', max_length=256, verbose_name='call-to-action text')),
            ],
            options={
                'verbose_name': 'site branding',
                'verbose_name_plural': 'site branding',
            },
        ),
    ]
