# Generated by Django 4.2.17 on 2026-02-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0011_sitebranding_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebranding',
            name='color_scheme',
            field=models.CharField(choices=[('classic', 'Classic (warm gold)'), ('ocean', 'Ocean (blue)'), ('forest', 'Forest (green)'), ('berry', 'Berry (raspberry)'), ('slate', 'Slate (gray)'), ('relief', 'Relief (teal)'), ('custom', 'Custom')], default='classic', max_length=16, verbose_name='color scheme'),
        ),
    ]
